[package]
name = "eric_os"
version = "0.1.0"
authors = ["Eric Rabil <ericjrabil@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
